import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BrainIcon, MicIcon, SparklesIcon } from "lucide-react";

export function FeaturesSection() {
  return (
    <section className="py-16 bg-background">
      <div className="container px-8 md:px-16">
        <h2 className="text-4xl text-center text-balance font-semibold mb-16">
          Powerful features to accelerate your learning
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
          <FeatureCard
            icon={<BrainIcon className="size-8 text-blue-500" />}
            title="Spaced Repetition"
            description="Master vocabulary with scientifically-proven spaced repetition algorithms that optimize your study schedule for maximum retention."
          />
          <FeatureCard
            icon={<MicIcon className="size-8 text-green-500" />}
            title="Speaking Games"
            description="Practice pronunciation and conversational skills through interactive speaking exercises and real-world scenario games."
          />
          <FeatureCard
            icon={<SparklesIcon className="size-8 text-purple-500" />}
            title="AI-Powered Learning"
            description="Get personalized flashcards and content generated by advanced AI, tailored to your specific learning goals and interests."
          />
        </div>
      </div>
    </section>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <Card className="p-8 text-center">
      <CardHeader className="items-center">
        <div className="text-accent font-semibold mb-4">{icon}</div>
        <CardTitle className="text-2xl font-bold">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-lg text-muted-foreground">{description}</p>
      </CardContent>
    </Card>
  );
}